name: Deploy go Application

on:
  push:
    branches:
      - deploy-to-ec2


jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
        - name: Create.env
          run: echo "PORT=${{ secrets.PORT }}"